# Generated by Django 4.1.3 on 2022-11-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_alter_vagas_tecnologias_estudar'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='tecnologias_estudar',
            field=models.ManyToManyField(related_name='estudar', to='empresa.tecnologias'),
        ),
    ]
