# Generated by Django 4.1.3 on 2022-11-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_vagas_email_alter_vagas_tecnologias_estudar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='tecnologias_estudar',
            field=models.ManyToManyField(blank=True, related_name='estudar', to='empresa.tecnologias'),
        ),
    ]
